services:
  ainewsbot_app:
    build: .
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app
    environment:
      - LEMMY_INSTANCE=${LEMMY_INSTANCE}
      - LEMMY_USERNAME=${LEMMY_USERNAME}
      - LEMMY_PASSWORD=${LEMMY_PASSWORD}
      - LEMMY_COMMUNITY=${LEMMY_COMMUNITY}

      - POST_REVIEW=${POST_REVIEW}
      - DATABASE_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@ainewsbot_db:5432/${POSTGRES_DB}
    depends_on:
      - ainewsbot_db
    restart: always
    networks:
      - ainewsbot_bridge

  ainewsbot_db:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - ainewsbot_bridge

networks:
  ainewsbot_bridge:
    driver: bridge
    